#! /bin/sh

export SHELL=/usr/bin/bash

sxhkd &
picom -cC --backend glx -r 42 -t "-30" -l "-40" -o .65 --corner-radius 6 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color '#FFFFFF'

bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a xfce4-terminal state=floating

~/Documents/script.sh | lemonbar -p &
hsetroot -solid '#81A3D0' &
xfce4-terminal 


